name: master - build and NuGet publish

on:
  push:
    branches:
      - main

env:
  BuildConfiguration: release
  Solution: Pug.HttpApiClient.sln
  HttpApiClientProject: Pug.HttpApiClient/Pug.HttpApiClient.csproj
  CommonProject: Pug.HttpApiClient.Common/Pug.HttpApiClient.Common.csproj
  OAuth2HttpApiClientProject: Pug.HttpApiClient.OAuth2/Pug.HttpApiClient.OAuth2.csproj
  PackagesBaseFolder: packages

jobs:
  build:
    name: Build and publish NuGet packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Authenticates packages to push to GPR
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/ndwx/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Restore NuGet packages
        run: dotnet restore ${{env.Solution}}

      - name: Build Models project
        run: dotnet build --nologo --no-restore --configuration ${{env.BuildConfiguration}} ${{env.HttpApiClientProject}}

      - name: Build Common project
        run: dotnet build --nologo --no-restore --configuration ${{env.BuildConfiguration}} ${{env.CommonProject}}

      - name: Build Main project
        run: dotnet build --nologo --no-restore --configuration ${{env.BuildConfiguration}} ${{env.OAuth2HttpApiClientProject}}

      - name: Create packages base folder
        run: mkdir packages

      - name: Pack HttpApiClient project
        run: dotnet pack --no-build --output ${{env.PackagesBaseFolder}} --nologo --configuration ${{env.BuildConfiguration}} ${{env.HttpApiClientProject}}

      - name: Publish HttpApiClient NuGet package to NuGet.org
        run: dotnet nuget push ${{env.PackagesBaseFolder}}/*.nupkg --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Clear packages folder
        run: rm packages/*.nupkg

      - name: Pack Common project
        run: dotnet pack --no-build --output ${{env.PackagesBaseFolder}} --nologo --configuration ${{env.BuildConfiguration}} ${{env.CommonProject}}

      - name: Publish Common NuGet package to NuGet.org
        run: dotnet nuget push ${{env.PackagesBaseFolder}}/*.nupkg --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Clear packages folder
        run: rm packages/*.nupkg

      - name: Pack OAuth2HttpApiClient project
        run: dotnet pack --no-build --output ${{env.PackagesBaseFolder}} --nologo --configuration ${{env.BuildConfiguration}} ${{env.OAuth2HttpApiClientProject}}

      - name: Publish OAuth2HttpApiClient NuGet package to NuGet.org
        run: dotnet nuget push ${{env.PackagesBaseFolder}}/*.nupkg --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Clear packages folder
        run: rm packages/*.nupkg